### ISSUE TITLE
(Another) decodePackBits panic

### ISSUE THREAD

**Issue by chocolatkey** [oov/psd#13]
This seems to be similar to other issues that have been reported and fixed:
```
github.com/oov/psd.decodePackBits(0xc000680000, 0x84db28, 0x84db28, 0xa6eb60, 0xc000092210, 0x26c1, 0x1b68, 0x0, 0x100000000000190, 0x0, ...)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/compress_other.go:65 +0x8fd
github.com/oov/psd.CompressionMethod.Decode(0xa60001, 0xc000680000, 0x84db28, 0x84db28, 0xa6eb60, 0xc000092210, 0x0, 0x0, 0x0, 0x26c1, ...)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/compress.go:35 +0x292
github.com/oov/psd.Decode(0xa6eb60, 0xc000092210, 0xc00019f7d0, 0xc000000001, 0xc000092210, 0x0, 0x0)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/psd.go:269 +0x83a
---
runtime error: slice bounds out of range [:17401434] with capacity 8706856
```

The file that I am trying to open is available here (warning partially NSFW):
[removed]

**Comment by oov** [comment]
It didn't cause any errors in my environment.
Is the error log really the full text?

**Comment by chocolatkey** [comment]
Strange, here is more relevant data:

- Running on Linux x64
- go.mod: require `github.com/oov/psd v0.0.0-20201203182240-dad9002861d9`

```go
// [...]
f, err := os.Open(binPath)
if err != nil {
	return nil, errors.Wrapf(err, "file for %s not openable after statting", resource.ID)
}
defer f.Close()

psx, _, err := psd.Decode(f, &psd.DecodeOptions{SkipLayerImage: true}) // <-- Line 421
if err != nil {
	return nil, errors.Wrapf(err, "PSD %s (%s) not decodable", resource.ID, resource.Meta.Filename)
}
// [...]
```

Log:
```
asynq: pid=4152254 2021/06/10 03:22:00.110424 ERROR: recovering from panic. See the stack trace below for details:
goroutine 51 [running]:
runtime/debug.Stack(0xc00019ef58, 0x979360, 0xc000212018)
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x9f
github.com/hibiken/asynq.(*processor).perform.func1(0xc000300000, 0xc00019ff70)
        /home/e4p/go/pkg/mod/github.com/hibiken/asynq@v0.17.1/processor.go:352 +0x76
panic(0x979360, 0xc000212018)
        /usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/oov/psd.decodePackBits(0xc000680000, 0x84db28, 0x84db28, 0xa6eb60, 0xc000092210, 0x26c1, 0x1b68, 0x0, 0x100000000000190, 0x0, ...)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/compress_other.go:65 +0x8fd
github.com/oov/psd.CompressionMethod.Decode(0xa60001, 0xc000680000, 0x84db28, 0x84db28, 0xa6eb60, 0xc000092210, 0x0, 0x0, 0x0, 0x26c1, ...)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/compress.go:35 +0x292
github.com/oov/psd.Decode(0xa6eb60, 0xc000092210, 0xc00019f7d0, 0xc000000001, 0xc000092210, 0x0, 0x0)
        /home/e4p/go/pkg/mod/github.com/oov/psd@v0.0.0-20201203182240-dad9002861d9/psd.go:269 +0x83a
PRIVATE/image.ExportImageSandbox(0xc00019fd98, 0xc00019fd38, 0xc00028e9d0, 0xd, 0xc00028e9c4, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
        PRIVATE/export.go:421 +0x1ac
```

**Comment by chocolatkey** [comment]
My apologies that was the wrong file I linked, it'shttps://b2.epub.rocks/file/hazepub/test/22a0657e-d34b-56a7-b730-b73b66203180.psd

**Comment by oov** [comment]
Thank you, the same error was reproduced.
I will investigate this issue.

**Comment by oov** [comment]
This file contains a compressed 1-bit bitmap, which was not supported by this package.
The reason is that I had only uncompressed 1-bit bitmaps available at the time of development.
But now we have the actual file, so I implemented it.

**Comment by chocolatkey** [comment]
Thank you very much, I updated the library and it works as expected.
